# Generated by Django 4.2.7 on 2024-04-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
