# Generated by Django 4.2.7 on 2024-04-11 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_number', models.CharField(max_length=255, unique=True, verbose_name='Authorization Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('merchant_number', models.CharField(max_length=255, verbose_name='Merchant Number')),
                ('merchant_email', models.EmailField(max_length=254, verbose_name='Merchant Email')),
                ('merchant_name', models.CharField(max_length=255, verbose_name='Merchant Name')),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent_to_merchant', 'Sent to Merchant'), ('processing_by_paymee', 'Processing by Paymee'), ('processing_by_bank', 'Processing by Bank'), ('won', 'Won'), ('lost', 'Lost')], max_length=100, verbose_name='Status')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('files', models.FileField(blank=True, null=True, upload_to='chargebacks/', verbose_name='Files')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chargebacks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chargebacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chargeback',
                'verbose_name_plural': 'Chargebacks',
            },
        ),
    ]
