# Generated by Django 4.2.7 on 2024-04-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_chargeback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chargeback',
        ),
    ]
