# Generated by Django 4.2.7 on 2024-05-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargebacks', '0002_rename_created_at_comment_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chargeback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargebacks.chargeback'),
        ),
    ]
