# Generated by Django 4.2.7 on 2024-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargebacks', '0003_remove_comment_creation_date_comment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeback',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent_to_merchant', 'Sent to Merchant'), ('processing_by_paymee', 'Processing by Paymee'), ('processing_by_bank', 'Processing by Bank'), ('won', 'Won'), ('lost', 'Lost'), ('desactivated', 'Desactivated'), ('reactivate', 'Reactivate')], default='created', max_length=100, verbose_name='Status'),
        ),
    ]
