# Generated by Django 4.2.7 on 2024-05-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargebacks', '0005_notificationsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
