# Generated by Django 4.2.7 on 2024-06-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargebacks', '0007_comment_created_at_comment_dislikes_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='chargeback_files/'),
        ),
    ]
