# Generated by Django 4.2.7 on 2024-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargebacks', '0008_file_uploaded_at_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
